version: '2'
services:
  refocus-app:
    build: .
    ports:
     - "3000:3000"
    depends_on:
     - "redis"
     - "pg"
  redis:
    image: "redis:3.2.8"
    expose:
       - 6379
  pg:
    image: "postgres:9.6.2"
    expose:
       - 5432

